language: minimal
sudo: required
services:
- docker
before_script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
- make push
env:
  global:
  - secure: QAQrgdMsL0Ii/+MIPtU8Zwp64/m8J0qZs/cDITQE8p5TCO868iJBPWOCKaD06WhvI3oOyRuPVyD/7wqVadXpxFVswLm7fF99m/7B8x/ffIbr8QC4keR3soi5GOUgQSMG1dSU4mVKQqZyj/oBvvkNoWCQcP7857NfsrWV8FIEmDlwKDhHNgTfiVAx1pKpytRVbbc+OL1Pnf8wM06I6h/4IHYcKM9t1b4qpRuKuAxRb8kz9ob8NOZrxwEzQPwmvFbfi5S0FjNlqO84Bi2+eM5+M1JKgFm5HoMx0doj9CZvtCwMF47OZkI5jRl2S3pEFQvm80pjMoyeBONllyhOLUJ2jSRqxfo+9Qez3soXklyvxJeMD+tL5WfyVzjAD1yL0oJcaMoa5nI0C3CN62dn4cRZZxqaOLd2eFyfHzwSKDMsC+vH5VygMJzmCZGcoDanaG22Hs1QfADujTPgP0nwWp/EBruIFYAEDDdE2EmQc7rTIEqdxDkSdubvEzz1eUBTuBgi3RZnpYd2WuKTukzGATfj1D5U1zPwf/EtphxNDE19/PvZ3vCaqlp113dxafq1AHb970V6rfB5vlrcrj62rwpFT8PxslbifRkSv6ZHGatsGL2jgJyDl4E2dcDVl2vOsT0safPTPAX3Zmy+wkcE2pjDPVU6eq4+q6nH/fGTORit5TA=
