language: minimal
sudo: required
services:
- docker
before_script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
- make push
env:
  global:
  - secure: zRJvFnZWqIaLzO+LBeZMM46BjP82dstCgclamAnm+yDD9bkV0vnjB3vT0TwaK2UeJrpdmySsa1p9XG2PN1zbfeVlP/3ew2rlJQ9SY6YU4WgWBH2kO9GMoCfv/2r+ZPEawVQ84jT7e1MdocbclSrSKDbXsS8BLHigKXVzoo89BYBf6bJyNpjDPxXkkLgsouLHvajKUktazQTXdXxAVPdw2POgXS7e8uEVplbPgcnOuu0N/aPZ00VryGBXTcs2f3ZDV4voXD7CN3zuBllKHT+AFalyGNTShX1JaJM48P1ZV/8ndR+GJgG2hWkMFuCgw4uRE+H6BHJnzfK6Ya77NdWifZ6nKImj9aXq9ZSbHhbcPaKR0TlR5fk5HRtZrE/dCZQJYyZM6XtGy0S79qMWcSXIazlTTmjR7dGRVyjwpHFnbNIb20cObbnFIO2kzIs+bTaQSNZqJAw6bNx246O2KZTjYJ8HZ0rTYbfcghetTSO+gW90sFo/9H1ZnBCGPYLFZP8f6RB3I1aiQUBxfQ9lcNmLZkYIBfYWXj6WFy12TxjLHTjt/JEOuaUHePlVWBtzbUV4kTQM7LubD7QDGSxW6anBvI/DUDyg9xMCk4J1Ea7Ooc7dq4t1pKe6uX1cHu8iExmcdQ/2G0FxmaigTsqjDB9E64P+ymwRmQNOkfL0QeswMW0=
  - secure: QU+SYsEVKMIBzIqMzjlxOg1dx5dT7/dd0wLqQz0JJppVIyys1SFtysjL2PlpYTHEVz9Vb1dYTob6rdyfrW/eJW3oq08wi0qFvbsiz4nNTIyjP2nodg/MYqrB7mQc4bGfEUUKoRYt0beKUSCdyPrJRTMqIt8OgKGQ/dgig9GFdA2CjphL4eyV+qM6hjFtL60+2TaJlHuat1q5+u1/XWgeO+3+gptZO0Ozt/h7xgigdOxfzamnZVVOvIqQIr7qnhYkXk2hJs3h4tiouiN7UiLZajYkvWtdJ8GOdp49WlCEYH1UVkgZMigYyCQGGSoIP8r2sBrXD2mcesBUfEaNVQDRGv2XfH88/APItXMbWixI6vCyLXzEuYF11o0WHZeq2OYh+RWSxN8ABL03YpEW7w0R1xpcjcxgNrChrghbTcZgONwuWWJasO/HGIqbNEHt+IFCPacciWTWk3ZjrSQ9+aKZv71Kj0B66+hCBf8CxmwSLsBtFCVv0tuX8EqDW3+OQNiuQc7F5EkX1eu9ARa/9WAz2UIw1DWWXKTHmNWFEFuDGfSHgqyvHi3Req79YV3+TNMJSZnLhtIEJClERVbutuNGqOrUWZcUh0MrtgSoNAV6c5Tmk8WKPrGjx3VQ5tIOU2gIG1rHo+vEpvWZqfZVO9mUqY63wNrf1mBJ7ysvR+sp8fg=
