language: minimal
sudo: required
services:
- docker
before_script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
- make push
env:
  global:
  - secure: i23RFAXcK8HtEANEE/lfewCVqb4l8YoeNGDZncaRx+/WjOJ4jeRYZ3cdYMLrVN7YyFGgCsUAKK4/l9Bngw7/kuUkv++QlQWprqVCf5jCFKfN6KWQV10a7dC0Cn7XsLJGySCOFHYZwwoIXjuOf2moAhbeOZVDKsFoULFkFgXrURNr9N5FqyPc1iA/RZj0qQ0/phyWx7des2EB8eGzhZkIzsvtoMBYlL/o5DJyhmIlN4Z7SYMGMzwhUAiSYhbB4aJl/5I+cszUENQ8/VnLo17tSlxIZrpuoDOYnBXV1I71TXQu6RaI4DPwUg829DuGSVu9UsbhlBYjEaEbecucevG0iquEwQw+wTE5t/h8XoNvpvkqT9vE/ZiDysZ/kmn711oJyA9fQV8224TKZOfsrYtiNQoDg9neXSuZpw4DxlV9hgI9LZo/yMg0HFY5BiRCLqvaGrErpQuZt+PqThdof5sHRn7DuFiQKsC/NSyCfvpPWOGr/I1/s/hccAWabSiv54CLzY/oR0y3WEuW9JPnsX8iuOSFo9sQf2D22lt74S/BeVrFsxoivU9AFiESV7dC04T0/fp1deUWyXzAozQx3doUOek7ljgMk8c3FET4sHv1sKFZFF9MDnPsvzj28I4QiqeyDwwwMNATC4T3QZvSkaoO7oRNZkNrueiJwf3dx04Nd4M=
