name: build-latest

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: build images and push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "linux/amd64"
          - "linux/arm/v7"

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: prepare buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - name: get the version
        id: container
        uses: qmx/ghaction-container-tag@master
        with:
          dockerhub_namespace: "${{ secrets.DOCKERHUB_NAMESPACE }}"


      - name: convert the arch
        id: sane_arch
        uses: qmx/ghaction-docker-arch@master
        with:
          docker_arch: "${{ matrix.target }}"

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build
        run: docker buildx build --platform ${{ matrix.target }}  -o type=tar,dest=./wk-${{ steps.sane_arch.outputs.arch }}.tar -t "${{ steps.container.outputs.image }}:latest-${{ steps.sane_arch.outputs.arch }}" .

      - name: save intermediary state
        uses: actions/upload-artifact@v2
        with:
          name: wk-${{ steps.sane_arch.outputs.arch }}.tar
          path: ./wk-${{ steps.sane_arch.outputs.arch }}.tar
