name: build

on: [push]

jobs:
  build:
    name: build images and push
    runs-on: ubuntu-latest

    steps:

      - name: install qemu
        run: docker run --rm --privileged hypriot/qemu-register

      - name: checkout
        uses: actions/checkout@v1

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: check docker version
        run: docker buildx version

      - name: create buildx worker
        run: docker buildx create --use

      - name: build
        run: docker buildx build --platform=linux/arm/v7,linux/amd64 .
